// Staff data ordered exactly as CSV (LAMP 1)
const staffData = [
{no:1,nama:"Hardono, S. Pd",nip:"NIP. 197604272010011004",foto:"HARDONO.jpg",jam:18,beban:18,ket:"",
tugas:[{t:"Kepala Sekolah",rombel:"",jam:18}]},
{no:2,nama:"Rita B., S.Pd.",nip:"NIP. 198203152006042014",foto:"Rita B._ OKe.jpg",jam:28,beban:40,ket:"",
tugas:[{t:"Matematika Kelas XII",rombel:7,jam:28},{t:"Waka Kurikulum",rombel:"",jam:12}]},
{no:3,nama:"Ismir Sugianto, S.Pd",nip:"NIP. 197910122003121007",foto:"Ismir Sugianto.JPG",jam:20,beban:32,ket:"",
tugas:[{t:"Kimia Kelas XII 1, 5, 6, 7",rombel:4,jam:20},{t:"Waka Kesiswaan",rombel:"",jam:12},{t:"Koordinator Laboratorium Kimia",rombel:"",jam:""}]},
{no:4,nama:"Abdul Munawir, S.Pd",nip:"NIP. 198510302010011008",foto:"Abdul Munawir, S.Pd.jpg",jam:21,beban:33,ket:"",
tugas:[{t:"Pendidikan Jasmani, Olahraga, dan Kesehatan Kelas XII",rombel:7,jam:21},{t:"Waka Sarana dan Prasarana",rombel:"",jam:12},{t:"Bendahara Pengurus Barang",rombel:"",jam:""}]},
{no:5,nama:"Qomarul Hafidz As'ari, S.E.",nip:"NIP. 198009282014101003",foto:"QOMARUL HAFIDZ AS_ARI.jpg",jam:26,beban:40,ket:"",
tugas:[{t:"Ekonomi Kelas X dan XI 8",rombel:8,jam:26},{t:"Waka Hubungan Masyarakat",rombel:"",jam:12},{t:"Pembina Ekstrakurikuler Jurnalistik",rombel:"",jam:2},{t:"Pembina Olimpiade Ekonomi",rombel:"",jam:""}]},
{no:6,nama:"Tati Mulyanti, S.Pd.",nip:"NIP. 196909231995122005",foto:"TATI MULYANTI.png",jam:28,beban:31,ket:"",
tugas:[{t:"Bahasa Indonesia Kelas XII",rombel:7,jam:28},{t:"Koordinator Pembelajaran Berbasis Projek Kelas X 1",rombel:1,jam:2},{t:"Piket",rombel:"",jam:1}]},
{no:7,nama:"Achmad Moeklis, S.Pd.",nip:"NIP. 198211272006041007",foto:"Achmad Moeklis.jpeg",jam:48,beban:69,ket:"",
tugas:[{t:"BP / BK Kelas X dan XII",rombel:14,jam:48},{t:"Pendidikan Pancasila Kelas XI",rombel:8,jam:16},{t:"Pembina Ekstrakurikuler Silat",rombel:"",jam:2},{t:"Pembina Ekstrakurikuler Hidroponik",rombel:"",jam:2},{t:"Fasilitator Pendidikan Lingkungan Hidup",rombel:"",jam:""},{t:"Piket",rombel:"",jam:1}]},
{no:9,nama:"Abdul Wahab, S.Pd",nip:"NIP. 197910302006041009",foto:"Abdul Wahab, S.Pd.jpeg",jam:32,beban:37,ket:"",
tugas:[{t:"Matematika Kelas XI",rombel:8,jam:32},{t:"Wali Kelas XI 3",rombel:"",jam:2},{t:"Pembina Ekstrakurikuler Bulutangkis",rombel:"",jam:2},{t:"Pembina Terampil Numerasi",rombel:"",jam:""},{t:"Piket",rombel:"",jam:1}]},
{no:10,nama:"Suridah, S.Ag",nip:"NIP. 197206052007012041",foto:"Suridah, S.Ag.png",jam:21,beban:26,ket:"",
tugas:[{t:"Pendidikan Agama Islam Kelas XII",rombel:7,jam:21},{t:"Wali Kelas XII 2",rombel:"",jam:2},{t:"Pembina Ekstrakurikuler Rohani Islam (ROHIS) Putri",rombel:"",jam:2},{t:"Piket",rombel:"",jam:1}]},
{no:11,nama:"Muhammad Wahyudi, S.Pd.",nip:"NIP. 198103102012211002",foto:"MUHAMMAD WAHYUDI.png",jam:24,beban:37,ket:"",
tugas:[{t:"Bahasa Indonesia Kelas XI 1, 2, 3, 4, 5, 6",rombel:6,jam:24},{t:"Kepala Perpustakaan",rombel:"",jam:12},{t:"Pembina Debat Bahasa Indonesia",rombel:"",jam:""},{t:"Pembina Giat Literasi",rombel:"",jam:""},{t:"Piket",rombel:"",jam:1}]},
{no:12,nama:"Sabraniti SA, S.Pd.",nip:"NIP. 197907142012121002",foto:"Sabraniti. SA, S.Pd.JPG",jam:36,beban:39,ket:"",
tugas:[{t:"Geografi Kelas X dan XII 1, 3, 6",rombel:10,jam:36},{t:"Koordinator Pembelajaran Berbasis Projek Kelas XI 5",rombel:1,jam:2},{t:"Pembina Olimpiade Geografi",rombel:"",jam:""},{t:"Piket",rombel:"",jam:1}]},
{no:13,nama:"Neneng Qomariana, S.T, S.Pd.",nip:"NIP. 198009022008012026",foto:"Neneng Qomariana.jpg",jam:26,beban:31,ket:"",
tugas:[{t:"Fisika Kelas X dan XI 8",rombel:8,jam:26},{t:"Wali Kelas X 1",rombel:1,jam:2},{t:"Koordinator Pembelajaran Berbasis Projek Kelas XI 4",rombel:"",jam:2},{t:"Pembina Olimpiade Astronomi dan Kebumian",rombel:"",jam:""},{t:"Piket",rombel:"",jam:1}]},
{no:14,nama:"Muhammad Heldiannur, S.Pd",nip:"NIP. 198005252014101001",foto:"Muhammad Heldiannur, S.Pd.jpeg",jam:36,beban:39,ket:"",
tugas:[{t:"Biologi Kelas X dan XII 2, 4, 7",rombel:10,jam:36},{t:"Koordinator Pembelajaran Berbasis Projek Kelas XII 1",rombel:1,jam:2},{t:"Koordinator Laboratorium Biologi",rombel:"",jam:""},{t:"Piket",rombel:"",jam:1}]},
{no:15,nama:"Sundari, S.Pd",nip:"NIP. 198205172014102001",foto:"SUNDARI, S. Pd.jpg",jam:21,beban:39,ket:"",
tugas:[{t:"Bahasa Inggris Kelas XII",rombel:7,jam:21},{t:"Bahasa Inggris Tingkat Lanjut Kelas XI 1, 3, 7",rombel:3,jam:15},{t:"Koordinator Pembelajaran Berbasis Projek Kelas X 2",rombel:1,jam:2},{t:"Pembina Ekstrakurikuler Paduan Suara",rombel:"",jam:""},{t:"Pembina Debat Bahasa Inggris",rombel:"",jam:""},{t:"Piket",rombel:"",jam:1}]},
{no:16,nama:"Adi Wiyoto, S.Pd",nip:"NIP. 198101252006041008",foto:"ADI WIYOTO.jpeg",jam:30,beban:33,ket:"",
tugas:[{t:"Ekonomi Kelas XI 1, 5, 6, dan XII 1, 2, 3",rombel:6,jam:30},{t:"Wali Kelas XI 5",rombel:"",jam:2},{t:"Fasilitator Pendidikan Lingkungan Hidup",rombel:"",jam:""},{t:"Piket",rombel:"",jam:1}]},
{no:17,nama:"Ahmad, S.Pd.",nip:"NIPPPK. 197803212022211002",foto:"AHMAD,S.Pd.jpg",jam:28,beban:35,ket:"",
tugas:[{t:"Pendidikan Pancasila Kelas X dan XII",rombel:14,jam:28},{t:"Wali Kelas XII 1",rombel:"",jam:2},{t:"Pembina Empat Pilar",rombel:"",jam:""},{t:"Pembina Ekstrakurikuler Bola Voli",rombel:"",jam:2},{t:"Pembina Ekstrakurikuler Pramuka",rombel:"",jam:2},{t:"Piket",rombel:"",jam:1}]},
{no:18,nama:"Audi Morfi, SE",nip:"NIPPPK. 198110032022211006",foto:"Audi Morfi .png",jam:30,beban:33,ket:"",
tugas:[{t:"Prakarya dan Kewirausahaan Kelas XI dan XII",rombel:15,jam:30},{t:"Koordinator Pembelajaran Berbasis Projek Kelas XII 2",rombel:1,jam:2},{t:"Piket",rombel:"",jam:1}]},
{no:19,nama:"Moh. Syahrizal, S.Pd",nip:"NIPPPK. 198409112022211009",foto:"MOH. SYAHRIZAL_2026.png",jam:25,beban:26,ket:"",
tugas:[{t:"Sejarah Kelas X dan XI 7, 8",rombel:9,jam:25},{t:"Operator Sekolah",rombel:"",jam:""},{t:"Koordinator Laboratorium Komputer",rombel:"",jam:""},{t:"Piket",rombel:"",jam:1}]},
{no:20,nama:"Abd. Gani Bahtiar, S.Pd",nip:"NIPPPK: 199112062022211014",foto:"GANI okeee - Copy.jpg",jam:30,beban:35,ket:"",
tugas:[{t:"Matematika Tingkat Lanjut Kelas XI 1, 2, & XII 4, 5, 6, 7",rombel:6,jam:30},{t:"Wali Kelas XII 7",rombel:"",jam:2},{t:"Koordinator Pengelolaan Kinerja Guru",rombel:"",jam:2},{t:"Pembina Olimpiade Matematika",rombel:"",jam:""},{t:"Piket",rombel:"",jam:1}]},
{no:21,nama:"Emelda Mayrita, S.Sn",nip:"NIPPPK: 199601052022212014",foto:"Emelda Mayrita, S.Sn.jpeg",jam:14,beban:33,ket:"",
tugas:[{t:"Seni, Budaya, dan Prakarya Kelas X",rombel:7,jam:14},{t:"Seni dan Budaya Kelas XII",rombel:7,jam:14},{t:"Wali Kelas X 6",rombel:"",jam:2},{t:"Koordinator Pembelajaran Berbasis Projek Kelas XI 7",rombel:1,jam:2},{t:"Pembina Ekstrakurikuler Tari",rombel:"",jam:2},{t:"Piket",rombel:"",jam:1}]},
{no:22,nama:"Isriyadi, S.Pd",nip:"NIPPPK: 198408152022211025",foto:"Isriyadi...jpeg",jam:21,beban:27,ket:"",
tugas:[{t:"Pendidikan Jasmani, Olahraga, dan Kesehatan Kelas X",rombel:7,jam:21},{t:"Wali Kelas X 3",rombel:"",jam:2},{t:"Koordinator Pembelajaran Berbasis Projek Kelas XI 6",rombel:1,jam:2},{t:"Pembina Ekstrakurikuler Futsal",rombel:"",jam:2},{t:"Piket",rombel:"",jam:1}]},
{no:23,nama:"Rajudian Nur, S.Pd",nip:"NIPPPK: 198009022022211007",foto:"Rajudian Nur.jpeg",jam:21,beban:26,ket:"",
tugas:[{t:"Kimia Kelas X",rombel:7,jam:21},{t:"Wali Kelas X 4",rombel:"",jam:2},{t:"Koordinator Pembelajaran Berbasis Projek Kelas XI 8",rombel:1,jam:2},{t:"Piket",rombel:"",jam:1}]},
{no:24,nama:"Nurul Hajar, S.Pd",nip:"NIPPPK: 198606152022212065",foto:"foto Nurul Hajar, S.pd.jpeg",jam:28,beban:33,ket:"",
tugas:[{t:"Bahasa Indonesia Kelas X",rombel:7,jam:28},{t:"Wali Kelas X 2",rombel:"",jam:2},{t:"Koordinator Pembelajaran Berbasis Projek Kelas XI 1",rombel:1,jam:2},{t:"Piket",rombel:"",jam:1}]},
{no:25,nama:"Muhammad Khairunnas, S.Pd.I",nip:"NIPPPK. 198908292023211007",foto:"Muhammad Khairunnas.png",jam:24,beban:29,ket:"",
tugas:[{t:"Pendidikan Agama Islam Kelas XI",rombel:8,jam:24},{t:"Wali Kelas XI 4",rombel:"",jam:2},{t:"Pembina Ekstrakurikuler Rohani Islam (ROHIS) Putra",rombel:"",jam:2},{t:"Piket",rombel:"",jam:1}]},
{no:26,nama:"Misbahul Jannah, S.Pd",nip:"NIPPPK. 199109112023212013",foto:"Misbahul Jannah,S.Pd.png",jam:24,beban:45,ket:"",
tugas:[{t:"BP / BK Kelas XI",rombel:8,jam:24},{t:"Seni dan Budaya Kelas XI",rombel:8,jam:16},{t:"Koordinator Pembelajaran Berbasis Projek Kelas X 4",rombel:1,jam:2},{t:"Pembina Ekstrakurikuler PIK-Remaja",rombel:"",jam:2},{t:"Piket",rombel:"",jam:1}]},
{no:27,nama:"Dirga Yuandari, S.Pd",nip:"NIPPPK. 199101232023211003",foto:"DIRGA YUANDARI, S.Pd..jpg",jam:28,beban:35,ket:"",
tugas:[{t:"Matematika Kelas X",rombel:7,jam:28},{t:"Wali Kelas X 7",rombel:"",jam:2},{t:"Koordinator Pembelajaran Berbasis Projek Kelas XI 3",rombel:1,jam:2},{t:"Pembina Ekstrakurikuler Basket",rombel:"",jam:2},{t:"Piket",rombel:"",jam:1}]},
{no:28,nama:"Vina Agustina, S.Pd",nip:"NIPPPK. 199008032024212030",foto:"Vina Agustina,S.Pd.jpeg",jam:30,beban:35,ket:"",
tugas:[{t:"Fisika Kelas XI 5, 6, 7, dan XII 1, 2, 3",rombel:6,jam:30},{t:"Wali Kelas XII 3",rombel:"",jam:2},{t:"Koordinator Pembelajaran Berbasis Projek Kelas X 6",rombel:1,jam:2},{t:"Pembina Olimpiade Fisika dan Water Roket",rombel:"",jam:""},{t:"Piket",rombel:"",jam:1}]},
{no:29,nama:"Ari Adnan Rafi'i, S.Pd",nip:"NIPPPK. 199007172024211021",foto:"ARI ADNAN RAFI_I.png",jam:24,beban:31,ket:"",
tugas:[{t:"Pendidikan Jasmani, Olahraga, dan Kesehatan Kelas XI",rombel:8,jam:24},{t:"Koordinator Pembelajaran Berbasis Projek Kelas XI 2",rombel:1,jam:2},{t:"Pembina OSIS",rombel:"",jam:2},{t:"Pembina Ekstrakurikuler Sepak Bola",rombel:"",jam:2},{t:"Piket",rombel:"",jam:1}]},
{no:30,nama:"Sinta Puji Lestari, S.Pd",nip:"NIPPPK. 199503172024212028",foto:"Sinta Puji Lestari, S.Pd.png",jam:15,beban:45,ket:"",
tugas:[{t:"Kimia Kelas XI 1, 6, 8",rombel:3,jam:15},{t:"Biologi Kelas XI 3, 4, 7",rombel:3,jam:15},{t:"Informatika Kelas X 4, 5, 6, 7",rombel:4,jam:8},{t:"Wali Kelas XI 1",rombel:1,jam:2},{t:"Koordinator Pembelajaran Berbasis Projek Kelas XII 6",rombel:1,jam:2},{t:"Pembina Olimpiade Biologi",rombel:"",jam:""},{t:"Pembina UKS",rombel:"",jam:""},{t:"Pembina Ekstrakurikuler PMR Putri",rombel:"",jam:2},{t:"Piket",rombel:"",jam:1}]},
{no:31,nama:"Nur Annisa, S.Pd",nip:"NIPPPK. 199604052024212040",foto:"Nur Annisa, S.Pd.png",jam:15,beban:38,ket:"",
tugas:[{t:"Kimia Kelas XI 2, 3, 4",rombel:3,jam:15},{t:"Informatika Kelas X 1, 2, 3",rombel:3,jam:6},{t:"Wali Kelas XI 2",rombel:"",jam:2},{t:"Kepala Laboratorium",rombel:"",jam:12},{t:"Koordinator Pembelajaran Berbasis Projek Kelas XII 7",rombel:1,jam:2},{t:"Pembina Olimpiade Kimia",rombel:"",jam:""},{t:"Piket",rombel:"",jam:1}]},
{no:32,nama:"Muhammad Bahtiar, S.Pd.I",nip:"NIPPPK. 199106112024211012",foto:"Muhammad Bahtiar.jpeg",jam:21,beban:26,ket:"",
tugas:[{t:"Pendidikan Agama Islam Kelas X",rombel:7,jam:21},{t:"Wali Kelas X 5",rombel:"",jam:2},{t:"Pembantu Pengurus Barang",rombel:"",jam:""},{t:"Pembina UKS",rombel:"",jam:""},{t:"Pembina Ekstrakurikuler PMR Putra",rombel:"",jam:2},{t:"Piket",rombel:"",jam:1}]},
{no:33,nama:"Gianti Anjarwati, S.Pd",nip:"NIPPPK. 199912222024212010",foto:"GIANTI ANJARWATI.png",jam:35,beban:42,ket:"",
tugas:[{t:"Informatika Kelas XI 4, 5, 7, dan XII 2, 4, 5, 7",rombel:7,jam:35},{t:"Wali Kelas XI 7",rombel:"",jam:2},{t:"Koordinator Pembelajaran Berbasis Projek Kelas XII 3",rombel:"",jam:2},{t:"Pembina Ekstrakurikuler Paskhass",rombel:"",jam:2},{t:"Pembina Olimpiade Informatika",rombel:"",jam:""},{t:"Piket",rombel:"",jam:1}]},
{no:34,nama:"Heny Agustina Widyanasari, S.Pd",nip:"NIPPPK. 198408162025212015",foto:"HENY AGUSTINA WIDYANASARI, S.Pd WASKAT.png",jam:21,beban:36,ket:"",
tugas:[{t:"Bahasa Inggris Kelas X",rombel:7,jam:21},{t:"Bahasa Inggris Tingkat Lanjut Kelas XII 5, 6",rombel:2,jam:10},{t:"Wali Kelas XII 6",rombel:"",jam:2},{t:"Koordinator Pembelajaran Berbasis Projek Kelas X 5",rombel:1,jam:2},{t:"Piket",rombel:"",jam:1}]},
{no:35,nama:"Siti Fatimah, S.Pd",nip:"NIPPPK. 198907112025212020",foto:"Siti Fatimah.png",jam:21,beban:36,ket:"",
tugas:[{t:"Bahasa Inggris Kelas XI",rombel:7,jam:21},{t:"Bahasa Inggris Tingkat Lanjut Kelas XII 3, 4",rombel:2,jam:10},{t:"Wali Kelas XII 4",rombel:"",jam:2},{t:"Koordinator Pembelajaran Berbasis Projek Kelas X 7",rombel:"",jam:2},{t:"Piket",rombel:"",jam:1}]},
{no:36,nama:"Fitri Adi, S.Pd",nip:"NIPPPK. 199801292025211032",foto:"FITRI ADI S.Pd.jpg",jam:36,beban:41,ket:"",
tugas:[{t:"Sosiologi Kelas X dan XI 2, 3, 8",rombel:10,jam:36},{t:"Wali Kelas XI 8",rombel:"",jam:2},{t:"Koordinator Pembelajaran Berbasis Projek Kelas XII 4",rombel:1,jam:2},{t:"Piket",rombel:"",jam:1}]},
{no:37,nama:"Graciella Eunike Manapa, S.Pd",nip:"NIPPPK. 200206222025212008",foto:"GRACIELLA EUNIKE MANAPA.jpeg",jam:8,beban:33,ket:"",
tugas:[{t:"Bahasa Indonesia Kelas XI 7, 8",rombel:2,jam:8},{t:"Bahasa Indonesia Tingkat Lanjut Kelas XI 2, 4, 5, 6",rombel:4,jam:20},{t:"Wali Kelas XI 6",rombel:"",jam:2},{t:"Koordinator Pembelajaran Berbasis Projek Kelas XII 5",rombel:1,jam:2},{t:"Piket",rombel:"",jam:1}]},
{no:38,nama:"David Golddra Pamungkas Bramantya, S.Pd",nip:"NIPPPK. 200007292025211024",foto:"DAVID GOLDDRA.png",jam:26,beban:31,ket:"",
tugas:[{t:"Sejarah Kelas XI 1, 2, 3, 4, 5, 6, dan XII",rombel:13,jam:26},{t:"Wali Kelas XII 5",rombel:"",jam:2},{t:"Koordinator Pembelajaran Berbasis Projek Kelas X 3",rombel:1,jam:2},{t:"Piket",rombel:"",jam:1}]}
];
